language: c

sudo: false

addons:
  apt:
    packages:
    - apache2-dev
    - libmarkdown2-dev

install:
  - autoreconf -f -i
  - ./configure --with-apxs=/usr/bin/apxs --with-discount=/usr
  - make

script:
 - echo "skip test"
